### ISSUE TITLE
感谢开源，APIJSON 已支持 Milvus，发现部分问题希望解决

### ISSUE THREAD

**Issue by TommyLemon** [colorknight/moql-transx#1]
https://github.com/APIJSON/APIJSON-Demo/commit/a0e703d3702383753a99b97d23b8686dc8cc08c0
<img width="1531" alt="image" src="https://github.com/colorknight/moql-transx/assets/5738175/1a438f32-b33b-4140-b128-3afc0e97877f">

目前发现以下问题：
### 1.查不到数据会报错，希望不报错，直接返回 null
<img width="1523" alt="image" src="https://github.com/colorknight/moql-transx/assets/5738175/9fbf8ec6-fba9-4f0b-857e-63a07c1b336e">
<img width="1532" alt="image" src="https://github.com/colorknight/moql-transx/assets/5738175/4c9382c9-eb41-4b8c-90ee-03e2cb64ea38">

Caused by: java.lang.NullPointerException: Cannot invoke "io.milvus.grpc.SearchResults.getResults()" because the return value of "io.milvus.param.R.getData()" is null
	at org.datayoo.moql.querier.milvus.MilvusQuerier.toRecordSet(MilvusQuerier.java:160)
	at org.datayoo.moql.querier.milvus.MilvusQuerier.query(MilvusQuerier.java:140)
	at org.datayoo.moql.querier.milvus.MilvusQuerier.query(MilvusQuerier.java:118)
	at apijson.demo.DemoSQLExecutor.execute(DemoSQLExecutor.java:234)
	at apijson.orm.AbstractParser.executeSQL(AbstractParser.java:2032)
	... 71 more

### 2.似乎不支持 NOT, != 等 语法
SELECT `id`,`name` FROM `sys`.`apijson_user` WHERE  (  (vMatch(`vec`,'L2','[[1]]')) AND (`id` != 1)  )  LIMIT 0, 10
<img width="1532" alt="image" src="https://github.com/colorknight/moql-transx/assets/5738175/79afdbb4-0eb0-4825-9819-40edfb4c7f8a">
<img width="1532" alt="image" src="https://github.com/colorknight/moql-transx/assets/5738175/4743f8c9-196d-40d9-84ef-384777bb437e">
<img width="1532" alt="image" src="https://github.com/colorknight/moql-transx/assets/5738175/4c9382c9-eb41-4b8c-90ee-03e2cb64ea38">
Caused by: java.lang.NullPointerException: Cannot invoke "io.milvus.grpc.SearchResults.getResults()" because the return value of "io.milvus.param.R.getData()" is null
	at org.datayoo.moql.querier.milvus.MilvusQuerier.toRecordSet(MilvusQuerier.java:160)
	at org.datayoo.moql.querier.milvus.MilvusQuerier.query(MilvusQuerier.java:140)
	at org.datayoo.moql.querier.milvus.MilvusQuerier.query(MilvusQuerier.java:118)
	at apijson.demo.DemoSQLExecutor.execute(DemoSQLExecutor.java:224)
	at apijson.orm.AbstractParser.executeSQL(AbstractParser.java:2032)

SELECT `id`,`name` FROM `sys`.`apijson_user` WHERE  (  (vMatch(`vec`,'L2','[[1]]')) AND (`id` NOT  IN (1,2))  )  LIMIT 0, 10
<img width="1531" alt="image" src="https://github.com/colorknight/moql-transx/assets/5738175/03c707d0-6326-4b56-aca4-34e6a63b0ae9">
<img width="1532" alt="image" src="https://github.com/colorknight/moql-transx/assets/5738175/2e3e560a-bcfa-4180-bc9c-9fb1f0cddbfe">
<img width="1532" alt="image" src="https://github.com/colorknight/moql-transx/assets/5738175/e757c4e4-1a3d-4600-93a4-b6d993635bc7">
Caused by: java.lang.NullPointerException: Cannot invoke "Object.toString()" because "operand" is null
	at org.datayoo.moql.querier.milvus.MilvusQuerier.buildOperand(MilvusQuerier.java:319)
	at org.datayoo.moql.querier.milvus.MilvusQuerier.buildOperand(MilvusQuerier.java:292)
	at org.datayoo.moql.querier.milvus.MilvusQuerier.buildOperand(MilvusQuerier.java:281)
	at org.datayoo.moql.querier.milvus.MilvusQuerier.buildOperand(MilvusQuerier.java:297)
	at org.datayoo.moql.querier.milvus.MilvusQuerier.buildOperand(MilvusQuerier.java:281)
	at org.datayoo.moql.querier.milvus.MilvusQuerier.buildWhereClause(MilvusQuerier.java:270)
	at org.datayoo.moql.querier.milvus.MilvusQuerier.buildSearchParam(MilvusQuerier.java:230)
	at org.datayoo.moql.querier.milvus.MilvusQuerier.query(MilvusQuerier.java:138)
	at org.datayoo.moql.querier.milvus.MilvusQuerier.query(MilvusQuerier.java:118)
	at apijson.demo.DemoSQLExecutor.execute(DemoSQLExecutor.java:224)
	at apijson.orm.AbstractParser.executeSQL(AbstractParser.java:2032)

### 3.必须加 vMatch 和 LIMIT，缺少任何一个都会报错，且 LIMIT 必须带上偏移量(例如 LIMIT 0, 10)，希望做成可选

缺少 vMatch 报错 "Target field name cannot be null or empty"，这个是官方 SDK 的报错，看能不能推动解决或者兼容
<img width="1531" alt="image" src="https://github.com/colorknight/moql-transx/assets/5738175/29c2ab77-5b34-4732-9512-4517cd6dbeee">
<img width="1532" alt="image" src="https://github.com/colorknight/moql-transx/assets/5738175/ad7f84d0-1979-4abf-a907-91e85d8e5344">
Caused by: io.milvus.exception.ParamException: Target field name cannot be null or empty
	at io.milvus.param.ParamUtils.CheckNullEmptyString(ParamUtils.java:150)
	at io.milvus.param.dml.SearchParam$Builder.build(SearchParam.java:303)
	at org.datayoo.moql.querier.milvus.MilvusQuerier.buildSearchParam(MilvusQuerier.java:239)
	at org.datayoo.moql.querier.milvus.MilvusQuerier.query(MilvusQuerier.java:138)
	at org.datayoo.moql.querier.milvus.MilvusQuerier.query(MilvusQuerier.java:118)
	at apijson.demo.DemoSQLExecutor.execute(DemoSQLExecutor.java:234)
	at apijson.orm.AbstractParser.executeSQL(AbstractParser.java:2032)
	... 71 more
2024-01-04 10:59:00.850: 

目前 APIJSON 已兼容 Milvus 的 LIMIT，问题不大

**Comment by colorknight** [comment]
非常感谢你的测试发现，我们研究一下，尽快回复你的问题

**Comment by TommyLemon** [comment]
@colorknight  提了解决空指针问题的 PR：
https://github.com/colorknight/moql-transx/pull/2

**Comment by colorknight** [comment]
咱们写的sql语句有些问题。moql这个引擎，其sql中的语法与标准的sql语法尚有区别。比如你的sql：SELECT id,name FROM sys.apijson_user WHERE ( (vMatch(vec,'L2','[[1]]')) AND (id NOT IN (1,2)) ) LIMIT 0, 10。在内存中看到的是，SELECT 'id','name' FROM... 。这在很多数据库中是支持的，但是moql不支持这种表达方式。moql是按照java的一套基础常量、变量、表达式语法构建的，把sql中的列名视为了变量，当咱们写为'id'时，这个会被语法视为常量，导致无法与具体列进行映射了。所以查询时，列名是不允许用单引号引起来的。你的部分SQL可以按此调整完后再试试。vMatch，Limit必须带的问题我们看看是否可给出好的缺省方案。

**Comment by TommyLemon** [comment]
试过 col, `col`, "col" 这 3 种方式，不带引号虽然能临时解决命名映射问题，但可能因为命名和 SQL 关键词冲突而导致数据库引擎解析 SQL 报错，希望支持反引号或双引号

**Comment by colorknight** [comment]
列名反引号模式已支持，由于双引号模式我们已经在语法中挪做他用了，故而没支持此中书写方式了，你需要同步更新moql-meta。相关jar包已经发布。milvus的vMatch在2.3.1版本后也可以缺省不填了，所以我们没有做调整了。非常感谢你的宝贵意见，再次感谢！
